config/routes.rb
Rails.application.routes.draw do

  resources :politrees do
    resources :issues
  end
  post 'politrees/:id/leave', to: 'politrees#leave'
  post 'politrees/:id/join', to: 'politrees#join'

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  get 'users/new'
  post 'users/create'


  get '/home', to: 'home#home'

  root 'home#welcome'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :topic, presence: true
  validates :user_id, presence: true
  belongs_to :user
  belongs_to :politree
end

app/models/membership.rb
class Membership < ApplicationRecord
  validates :politree_id, presence: true
  validates :member_id, presence: true, uniqueness: {scope: :politree_id}
  belongs_to :member, class_name: User
end

app/models/politree.rb
class Politree < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :owner_id, presence: true
  belongs_to :owner, class_name: User
  has_many :memberships
  has_many :members, through: :memberships
  has_many :issues
end

app/models/remedy.rb
class Remedy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :phone, phone: true
  validates :email, confirmation: true, uniqueness: { case_sensitive: false }
  validates :email_confirmation, presence: true
  validates :username, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :init_flash

  before_action :authenticate

  def init_flash
    flash.alert = [] if flash.alert.nil? || flash.alert.empty?
    flash.notice = [] if flash.notice.nil? || flash.notice.empty?
  end

  def authenticate
    @user = User.find_by(id: session[:user_id])
    if @user.nil?
      flash.alert << 'you must be logged in to view that page!'
      redirect_to controller: :sessions, action: :new
    end
  end

  def antiauthenticate
    @user = User.find_by(id: session[:user_id])
    unless @user.nil?
      redirect_to controller: :home, action: :home
    end
  end

  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    reset_session
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate, only: [ :welcome ]
  before_action :antiauthenticate, only: [ :welcome ]

  def welcome
  end

  def home
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  before_action :validate_politree, only: [:new, :create]
  before_action :validate_member, only: [:new, :create]

  def show
  end

  def new
  end

  def create
    issue = @politree.issues.new(topic: params[:topic], description: params[:description], user_id: @user.id)
    unless issue.valid?
      issue.errors.messages.each do |attribute, errors|
        errors.each do |error|
          flash.alert << "#{attribute} #{error}"
        end
      end
      return redirect_to action: :new
    end
    issue.save!
    flash.notice << "created issue: \"#{issue.topic}.\""
    return redirect_to politree_issue_path @politree.id, issue.id
  end

  def validate_politree
    @politree = Politree.find(params[:politree_id])
    if @politree.nil? 
      flash.alert << "that politree does not exist"
      return redirect_to controller: :politrees, action: :index
    end
    @owner = @politree.owner
    @membership = @politree.memberships.where(member_id: @user.id).first
  end

  def validate_member
    if @membership.nil?
      flash.alert << "you must be a member of this politree to do that"
      return redirect_to politree_path(@politree.id)
    end
    @member = @membership.member
  end

end

app/controllers/politrees_controller.rb
class PolitreesController < ApplicationController
  
  before_action :validate_politree, only: [:show, :destroy, :join, :leave]
  before_action :validate_member, only: [:leave]

  def index
    @politrees = Politree.all
  end

  def show
  end

  def new
  end

  def create
    politree = Politree.new(name: params[:name], description: params[:description], owner_id: @user.id)
    unless politree.valid?
      politree.errors.messages.each do |attribute, errors|
        errors.each do |error|
          flash.alert << "#{attribute} #{error}"
        end
      end
      return redirect_to action: :new
    end
    politree.save!
    flash.notice << "created #{politree.name}."
    return redirect_to politree_path politree.id
  end

  def destroy
    unless @politree.owner == @user
      flash.alert << "only the owner of this politree may delete it"
      return redirect_to action: :show, id: @politree.id
    end
    flash.notice << "deleted #{@politree.name}"
    @politree.destroy!
    redirect_to action: :index
  end

  def join
    if @membership.nil?
      @politree.memberships.create!(member_id: @user.id)
    else
      flash.alert << "you are already a member of '#{@politree.name}'"
    end
    flash.notice << "you have joined '#{@politree.name}'"
    redirect_to politree_path(@politree.id)
  end

  def leave
    @membership.destroy!
    flash.notice << "you have left '#{@politree.name}'"
    redirect_to politree_path(@politree.id)
  end

  def validate_politree
    @politree = Politree.find(params[:id])
    if @politree.nil? 
      flash.alert << "that politree does not exist"
      return redirect_to action: :index
    end
    @owner = @politree.owner
    @membership = @politree.memberships.where(member_id: @user.id).first
  end

  def validate_member
    if @membership.nil?
      flash.alert << "you must be a member of this politree to do that"
      return redirect_to politree_path(@politree.id)
    end
    @member = @membership.member
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authenticate, only: [:new, :create]
  before_action :antiauthenticate, only: [:new, :create]

  def new

  end

  def create
    user = User.find_by(username: params[:username].downcase)
    if user && user.authenticate(params[:password])
      log_in user
      session[:user_id] = user.id
      flash.notice << "hello, #{user.username}!"
      redirect_to controller: :home, action: :home
    else
      flash.alert << 'wrong username or password'
      redirect_to action: :new
    end
  end

  def destroy
    log_out
    flash.notice = ["you are now logged out"]
    redirect_to action: :new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :authenticate, only: [:new, :create]
  before_filter :antiauthenticate, only: [:new, :create]

  def new
  end

  def create
    user = User.create(params.permit(:username, :phone, :email, :email_confirmation, :password, :password_confirmation))
    unless user.valid?
      user.errors.messages.each do |attribute, errors|
        errors.each do |error|
          flash.alert << "#{attribute} #{error}"
        end
      end
      return redirect_to action: :new
    end
    log_in user
    flash.notice << "welcome, #{user.username}."
    return redirect_to controller: :home, action: :home
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/politrees_helper.rb
module PolitreesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/home.html.erb
<div class='word stuff'>
  <p><%= image_tag 'person.png' %> This is you. 
</div>

app/views/home/index.html.erb
<div class='word stuff'>
  <p><%= image_tag 'person.png' %> This is you. 
</div>

app/views/home/welcome.html.erb
<div class='word stuff'>
  <p><%= image_tag 'person.png' %> This is you. 
</div>

app/views/issues/new.html.erb
<div class='form stuff'>
  <h1 class='title'>new issue for <%= @politree.name %></h1>
  <%= form_tag(politree_issues_path, method: 'post') do %>
    <input type='text' name='topic' placeholder='name of issue'></input>
    <input type='text' name='description' placeholder='description of issue'></input>
    <input type='submit' value='create'></input>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Murmur</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='bar'>
      <a href= '/' class='title'>project murmur</a>
      <div id='nav'>
        <%= link_to 'politrees', politrees_path %>
      </div>
      <% if @user.nil? %>
        <div id='quicklogin'>
          <%= form_tag('/sessions/create', method: :post) do %>
            <input type='text' name='username' placeholder='username'></input>
            <input type='password' name='password' placeholder='password'></input>
            <input type='submit' value='log in'></input>
          <% end %>
          or <a href='/users/new'>sign up</a>
        </div>
      <% else %>
        <div id='quickpanel'>logged in as <%= @user.username %>. (<a href="/sessions/destroy">log out</a>)</div>
      <% end %>
    </div>

    <% unless flash.alert.empty? %>
      <div id='alerts'>
        <% flash.alert.each do |alert| %>
          <span class="alert"><%= alert %></span>
        <% end %>
      </div>
    <% end %>

    <% unless flash.notice.empty? %>
      <div id='notices'>
        <% flash.notice.each do |notice| %>
          <span class="notice"><%= notice %></span>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/politrees/index.html.erb
<div class='word stuff'>
  <h1 class='title'>all politrees:</h1>
  <a href='/politrees/new'>create a new politree</a>
  <% @politrees.each do |tree| %>
    <p><a href='/politrees/<%= tree.id %>'><%= tree.name %></a>: <%= tree.description %></p>
  <% end %>
</div>

app/views/politrees/new.html.erb
<div class='form stuff'>
  <h1 class='title'>new politree</h1>
  <%= form_tag(politrees_path, method: 'post') do %>
    <input type='text' name='name' placeholder='politree name'></input>
    <input type='text' name='description' placeholder='politree description'></input>
    <input type='submit' value='create'></input>
  <% end %>
</div>

app/views/politrees/show.html.erb
<div class='word stuff'>
  <h1 class='title'><%= @politree.name %></h1>
  <p><%= @politree.description %></p>
  <hr></hr>
  <p class='title'>(created by <%= @owner.username %>)</p>
  <% if @user == @owner %>
    <%= form_tag(politree_path(@politree.id), method: :delete) do %>
      <input type='submit' value='delete this politree?'></input>
    <% end %>
  <% end %>
  <% if @membership.nil? %>
    <%= form_tag("#{politree_path(@politree.id)}/join", method: :post) do %>
      <input type='submit' value='join this politree?'></input>
    <% end %>
  <% else %>
    <%= form_tag("#{politree_path(@politree.id)}/leave", method: :post) do %>
      <input type='submit' value='leave this politree?'></input>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_tag('/users/create', method: :post) do %>

  <div class='form stuff'>
    
    <h1 class='title'>need an account?</h1>
    <input type='text' name='username' placeholder='username'></input>
    <input type='tel' name='phone' placeholder='phone number'></input>
    <input type='text' name='email' placeholder='email'></input>
    <input type='text' name='email_confirmation' placeholder='confirm email'></input>
    <input type='password' name='password' placeholder='password'></input>
    <input type='password' name='password_confirmation' placeholder='confirm password'></input>
    <input type='submit' value='create account'></input>

  </div>

<% end %>